// <auto-generated />
using System;
using LeitorMercadoLivre.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeitorMercadoLivre.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeitorDbContext))]
    [Migration("20260928061822_EixoDoTempo")]
    partial class EixoDoTempo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.CatalogProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.CollectionCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("WindowStart")
                        .IsUnique();

                    b.ToTable("cycles");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.DailyVisits", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text")
                        .HasColumnName("item_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visits")
                        .HasColumnType("integer")
                        .HasColumnName("visits");

                    b.HasKey("ItemId", "Date");

                    b.ToTable("visits");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.ExchangeRateQuote", b =>
                {
                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<DateOnly>("QuoteDate")
                        .HasColumnType("date")
                        .HasColumnName("quote_date");

                    b.Property<decimal>("Sell")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("sell");

                    b.HasKey("Currency", "RequestedDate");

                    b.ToTable("exchange_rates");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.HighlightSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<long>("CycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("cycle_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CollectedAt");

                    b.HasIndex("CycleId", "CategoryId", "ProductId")
                        .IsUnique();

                    b.ToTable("highlights");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.ListingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<long>("CycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("cycle_id");

                    b.Property<bool>("FreeShipping")
                        .HasColumnType("boolean")
                        .HasColumnName("free_shipping");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_id");

                    b.Property<string>("ListingTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("listing_type_id");

                    b.Property<string>("LogisticType")
                        .HasColumnType("text")
                        .HasColumnName("logistic_type");

                    b.Property<int>("MinPurchaseUnit")
                        .HasColumnType("integer")
                        .HasColumnName("min_purchase_unit");

                    b.Property<long?>("OfficialStoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("official_store_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seller_id");

                    b.Property<int?>("TotalVisits")
                        .HasColumnType("integer")
                        .HasColumnName("total_visits");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "ItemId")
                        .IsUnique();

                    b.HasIndex("ProductId", "CycleId");

                    b.ToTable("listings");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.OAuthCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.Operator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name_key");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("operators");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.ProductAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<string>("CeilingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ceiling_json");

                    b.Property<long>("CycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("cycle_id");

                    b.Property<string>("DemandJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("demand_json");

                    b.Property<string>("DemandPhase")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("demand_phase");

                    b.Property<decimal>("DemandScore")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("demand_score");

                    b.Property<string>("DemandSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("demand_source");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool?>("HasFreeShipping")
                        .HasColumnType("boolean")
                        .HasColumnName("has_free_shipping");

                    b.Property<bool?>("HasNewCondition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_new_condition");

                    b.Property<bool?>("HasUsedCondition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_used_condition");

                    b.Property<bool>("IsNewDemand")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_demand");

                    b.Property<int?>("LastWeekVisits")
                        .HasColumnType("integer")
                        .HasColumnName("last_week_visits");

                    b.Property<bool>("LowDemand")
                        .HasColumnType("boolean")
                        .HasColumnName("low_demand");

                    b.Property<string>("MarginJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("margin_json");

                    b.Property<decimal?>("MarketPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("market_price");

                    b.Property<int?>("NewSellers")
                        .HasColumnType("integer")
                        .HasColumnName("new_sellers");

                    b.Property<decimal?>("OpportunityIndex")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("opportunity_index");

                    b.Property<string>("OpportunityJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("opportunity_json");

                    b.Property<string>("PriceConfidence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("price_confidence");

                    b.Property<string>("PriceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("price_json");

                    b.Property<string>("PriceStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_status");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("Quadrant")
                        .HasColumnType("text")
                        .HasColumnName("quadrant");

                    b.Property<string>("RunwayJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("runway_json");

                    b.Property<decimal?>("RunwayWeeksLower")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("runway_weeks_lower");

                    b.Property<int>("SellersFound")
                        .HasColumnType("integer")
                        .HasColumnName("sellers_found");

                    b.Property<decimal?>("VisitGrowthPercent")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("visit_growth_percent");

                    b.Property<decimal?>("WorstMargin")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("worst_margin");

                    b.Property<bool?>("WorthImporting")
                        .HasColumnType("boolean")
                        .HasColumnName("worth_importing");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "ProductId")
                        .IsUnique();

                    b.HasIndex("ProductId", "CalculatedAt");

                    b.HasIndex("ProductId", "Id");

                    b.ToTable("analyses");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.SeenSeller", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("SellerId")
                        .HasColumnType("text")
                        .HasColumnName("seller_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.HasKey("ProductId", "SellerId");

                    b.HasIndex("ProductId", "FirstSeenAt");

                    b.ToTable("seen_sellers");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByOperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_operator_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("InternationalFreightTotal")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("international_freight_total");

                    b.Property<int>("MinimumOrder")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<int>("ShipmentQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_quantity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByOperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_operator_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text")
                        .HasColumnName("whats_app");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Active");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.VisitCoverage", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text")
                        .HasColumnName("item_id");

                    b.Property<DateOnly>("CoveredFrom")
                        .HasColumnType("date")
                        .HasColumnName("covered_from");

                    b.Property<DateOnly>("CoveredTo")
                        .HasColumnType("date")
                        .HasColumnName("covered_to");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ItemId");

                    b.ToTable("visit_coverage");
                });

            modelBuilder.Entity("LeitorMercadoLivre.Infrastructure.Persistence.WorkSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "StartedAt");

                    b.ToTable("work_sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
